### ISSUE TITLE
fi.giveMeMore

### ISSUE THREAD

**Issue by jenniferbusca** [learn-co-curriculum/js-advanced-functions-functional-library-project#1]
There is a test for giveMeMore that fails. Below is what is in the readme for giveMeMore. Is the intention for every student to reach out to their instructor for more function assignments in order to get the test to pass?

fi.giveMeMore
If you are reading this come to us for more functions assignments. Awesome daring!

**Comment by sgharms** [comment]
I think we were thinking that it was an inspiration to try more out on your own. We'll clarify this.
