### ISSUE TITLE
The sortBy() tests are very confusing in this lab.

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/js-advanced-functions-functional-library-project#2]
The tests for the sortBy() function in this lab are very confusing mainly because there are objects and callback functions that are not even used in the tests.  I spent 2+ hours stuck on this lab trying to figure out how to implement the solution and even the AAQ technical coach could not figure out as to why this data was in there.  If the tests are not actually implemented then they shouldn't be put into the test file as it just creates a lot of confusion for the student.

    const unsortedObjArr = [
      {name: "dennis", age: 29},
      {name: "dee", age: 40},
      {name: "mac", age: 34},
      {name: "charlie", age: 32},
      {name: "frank", age: 72}
    ]
    const controlSortedObjArr = [
      {name: "dennis", age: 29},
      {name: "charlie", age: 32},
      {name: "mac", age: 34},
      {name: "dee", age: 40},
      {name: "frank", age: 72}
    ]

    function sortObjFunction(obj) { return obj.age }

**Comment by Sdcrouse** [comment]
@merecka For future reference, I figured out a way to do it, but it only works on Objects if their values are numbers, not strings.

For the example above, the sortBy() function could effectively do this:
```
unsortedObjArrCopy.sort( (objA, objB) => sortObjFunction(objA) - sortObjFunction(objB) );
```

I got the idea from one of the lab resources: https://www.w3schools.com/js/js_array_sort.asp
