### ISSUE TITLE
Possible test bug - describe 'uniq'

### ISSUE THREAD

**Issue by khongcodes** [learn-co-curriculum/js-advanced-functions-functional-library-project#4]
Hope I'm not crazy for thinking this is odd!

Starting line 243 on test/indexTest.js:
`it('removes duplicate values from an array when an iteratee is applied', function () {
      const newArr = fi.uniq([1, 2, 2, 3, 4, 6, 9], false, (val => val % 3))
      console.log(newArr)
      expect(arraysEqual(newArr, [1, 2, 3])).to.equal(true)
    })`

Specifically that last line; the expected return is [1, 2, 3]. Would it not be impossible to get a return value of 3 from a function that returns (val % 3)?
I've modified my own file so that that line reads instead:

`      expect(arraysEqual(newArr, [1, 2, 0])).to.equal(true)`

**Comment by rrcobb** [comment]
This one is definitely a little confusing! 

The return values from the callback to `fi.uniq` aren't used to generate the values in the output. Instead, they're used to check the values of the input array, to decide if they should be included in the output. You should only get values in the output that showed up in the input - no new values.

This is confusing enough that it warranted some clarification, added in ed12099.
