### ISSUE TITLE
Improper math in assertion?

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/js-advanced-functions-functional-library-project#5]
In the test for the reduce function the condition [it("returns the correct reduced value when not passed an accumulator", function()] expects the reduction to return 28.
Shouldn't the return be 30?
(1*3)+(2*3)+(3*3)+(4*3)

**Comment by Sdcrouse** [comment]
If you don't give the reduce function an initial value/accumulator, then the accumulator is set to the first value in the collection.

In this case, the test looks something like this: 
```
const testArr = [1,2,3,4]
callback = (acc, val, collection) => (acc + (val * 3))
reduceSansAcc = fi.reduce(testArr, callback)
```

- In the first iteration/call to the callback, acc = 1, val = 2, and the callback returns 1 + (2 * 3) = 7
- In the second iteration, acc = 7, val = 3, and the callback returns 7 + (3 * 3) = 16
- In the final iteration, acc = 16, val = 4, and the callback returns 16 + (4 * 3) = 28

So yes, the return value of the reduce function is supposed to be 28 in this case.

If the reduce function were supposed to initialize the accumulator to 0 by default, then yes, it should return 30. However, as I said above, the reduce function is supposed to initialize the accumulator to the first value in the collection by default.

Hope that helps!

**Comment by lizbur10** [comment]
Hi there! 

Thanks again for helping out @Sdcrouse! 

Hopefully Steven's explanation made sense but if you still have questions about this, you are free to post a question on [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) 

Thanks for contributing! 💙

**Comment by Sdcrouse** [comment]
@lizbur10 You're welcome, again!
