### ISSUE TITLE
Math Error?

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/js-advanced-functions-functional-library-project#6]
In the test [it("removes duplicate values from an array when an iteratee is applied"] the expectation is a new array of [1,2,3]. However, wouldn't performing %3 on each of those values actually produce an array of [0,1,2]?

**Comment by Sdcrouse** [comment]
@skmcloughlin You're close, but `uniq` isn't supposed to return an array of the unique return values of `val => val % 3`. It's supposed to return the first values of the original array that correspond to those unique return values. 

I think the Readme explains it better:

> Specifically, if the callback function returns the same value that a previous execution of the callback also returned, we don't include that item in the return array - even if the original array's elements are different. The output array will be made up of a subset of the values of the original array - not the transformed values.

I know you're way beyond this point, but I hope that helps a little.

**Comment by lizbur10** [comment]
Hi there! 

Thanks for helping out @Sdcrouse! 

Hopefully Steven's explanation made sense but if you still have questions about this, you are free to post a question on [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) 

Thanks for contributing! 💙

**Comment by Sdcrouse** [comment]
@lizbur10 You're welcome, and glad to help! That lab can get tricky.
