### ISSUE TITLE
Link in Instructions section is broken

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/js-advanced-functions-functional-library-project#9]
In the **Instructions** section, there's a light-blue link labeled "Immediately Invoked Function Expression".

![image](https://user-images.githubusercontent.com/38870640/82771828-1fd63580-9df2-11ea-86e2-7399fddbc209.png)

However, I can only hover my cursor over it; it doesn't go anywhere. It looks like a Markdown issue, so I'll fix it in a pull request.

**Comment by lizbur10** [comment]
Thanks again for contributing! 💙
